#pragma once
#include <filesystem>
#include <iostream>
#include <stdio.h>
#include <string.h>
#include <gtest/gtest.h>
#include <gmock/gmock.h>
#include "../src/lexer/lexer.h"
#include "../src/parser/parser.hpp"