#define NEW_LINE 1
#define DECIMAL 2
#define NUMBER 3
#define IDENTIFIER 4
#define PRINT 5
#define OPEN_PARANTHESIS 6
#define CLOSED_PARANTHESIS 7
#define EQUAL 8
#define PLUS 9
#define MINUS 10
#define MULTIPLY 11
#define DIVIDE 12
#define MODULO 13
#define AND 14
#define OR 15
#define NOT 16
#define FUNCTION 17
#define COMMA 18
#define BOOLVAL 19
#define FOR 20
#define WHILE 21
#define COLON 22
#define IF 23
#define ELSE 24
#define RETURN 25
#define OPEN_SQUAREBRACKET 26
#define CLOSED_SQUAREBRACKET 27
#define DOT 28
#define IS 29
#define TAB_INDENT 30
#define TAB_DEDENT 31