#define NEW_LINE 1
#define DECIMAL 2
#define NUMBER 3
#define IDENTIFIER 4
#define PRINT 5
#define OPEN_PARANTHESIS 6
#define CLOSED_PARANTHESIS 7
#define EQUAL 8
#define PLUS 9
#define MINUS 10
#define MULTIPLY 11
#define DIVIDE 12
#define MODULO 13
#define AND 14
#define OR 15
#define NOT 16
#define FUNCTION 17
#define ARGUMENTSPLIT 18
#define TRUE 19
#define FALSE 20
#define FOR 21
#define WHILE 22
#define COLON 23
#define IF 24
#define ELSE 25
#define RETURN 27
#define OPEN_SQUAREBRACKET 28
#define CLOSED_SQUAREBRACKET 29
#define DOT 30
#define IS 31
